### ISSUE TITLE
Create graph showing request statuses per project

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/log-offload#2]
- Show # requests per URL
- Show status codes

**Comment by lucasvanhalst** [comment]
![screen shot 2018-02-13 at 15 25 05](https://user-images.githubusercontent.com/6652304/36154540-190f76da-10d2-11e8-838e-3ae162c2ed78.png)

can't seem to make it stack the graphs so same url has 1 bar with different parts. perhaps we should split it up in 2 graphs, one for all requests and one for failed requests (so status 4xx-5xx)
